//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tableQLCT
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> date1 { get; set; }
        public int money1 { get; set; }
        public string ghichu { get; set; }
    }
}
